#!/usr/bin/env python3
"""
SIH26145 — CICIDS2017 Data Preparation Script.

Prepares the real CICIDS2017 dataset for training a Random Forest
binary classifier (BENIGN vs ATTACK).

CICIDS2017 provides flow-level CSV files generated by CICFlowMeter.
These files contain labeled network flows from a simulated network
with benign and various attack traffic.

INPUT:
    A directory containing CICIDS2017 CSV files, OR a single CSV file.
    The official CICIDS2017 MachineLearningCSV directory contains:
      - Monday-WorkingHours.pcap_ISCX.csv
      - Tuesday-WorkingHours.pcap_ISCX.csv
      - Wednesday-WorkingHours.pcap_ISCX.csv
      - Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
      - Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
      - Friday-WorkingHours.pcap_ISCX.csv
      - Friday-WorkingHours-Attacks.pcap_ISCX.csv

OUTPUT:
    backend/training/data/cicids2017_cleaned.csv
    backend/training/data/feature_info.joblib

USAGE:
    cd backend
    python training/prepare_cicids2017.py /path/to/MachineLearningCSV/

FEATURE MAPPING:
    CICIDS2017 columns → Our 12 ML features:

    CICIDS2017 Column                  → Our Feature
    ─────────────────────────────────────────────────
    Flow Duration                      → flowDuration
    Total Fwd Packets                  → totalFwdPackets
    Total Backward Packets             → totalBwdPackets
    Total Fwd Bytes + Total Bwd Bytes  → totalBytes (derived)
    Flow Bytes/s                       → bytesPerSecond
    Flow Packets/s                     → packetsPerSecond
    Destination Port                   → destinationPort
    Source Port                        → sourcePort
    Packet Length Mean                 → packetLengthMean
    Packet Length Std                  → packetLengthStd
    Fwd Packet Length Mean             → fwdPacketLengthMean
    Bwd Packet Length Mean             → bwdPacketLengthMean
    (NOT AVAILABLE)                    → sourceEntropy (dropped)
    (NOT AVAILABLE)                    → destinationConcentration (dropped)

LABEL MAPPING:
    CICIDS2017 original labels → Binary:
        BENIGN          → BENIGN
        DDoS            → ATTACK
        PortScan        → ATTACK
        Bot             → ATTACK
        Infiltration    → ATTACK
        Web Attack *    → ATTACK
        (all others)    → ATTACK

This script does NOT claim these are SIH26145 threat classes.
It is a binary BENIGN/ATTACK classifier trained on CICIDS2017 data.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd


# ── CICIDS2017 column name normalization ──────────────────────────
# CICIDS2017 CSVs have inconsistent leading/trailing whitespace in
# column names. This map normalizes them to clean snake_case.

_COLUMN_ALIASES: dict[str, str] = {
    "flow duration": "flow_duration",
    "total fwd packets": "total_fwd_packets",
    "total backward packets": "total_backward_packets",
    "fwd packets length total": "fwd_packets_length_total",
    "bwd packets length total": "bwd_packets_length_total",
    "fwd packet length max": "fwd_packet_length_max",
    "fwd packet length min": "fwd_packet_length_min",
    "fwd packet length mean": "fwd_packet_length_mean",
    "fwd packet length std": "fwd_packet_length_std",
    "bwd packet length max": "bwd_packet_length_max",
    "bwd packet length min": "bwd_packet_length_min",
    "bwd packet length mean": "bwd_packet_length_mean",
    "bwd packet length std": "bwd_packet_length_std",
    "flow bytes/s": "flow_bytes_s",
    "flow packets/s": "flow_packets_s",
    "flow iat mean": "flow_iat_mean",
    "flow iat std": "flow_iat_std",
    "flow iat max": "flow_iat_max",
    "flow iat min": "flow_iat_min",
    "fwd iat total": "fwd_iat_total",
    "fwd iat mean": "fwd_iat_mean",
    "fwd iat std": "fwd_iat_std",
    "fwd iat max": "fwd_iat_max",
    "fwd iat min": "fwd_iat_min",
    "bwd iat total": "bwd_iat_total",
    "bwd iat mean": "bwd_iat_mean",
    "bwd iat std": "bwd_iat_std",
    "bwd iat max": "bwd_iat_max",
    "bwd iat min": "bwd_iat_min",
    "fwd psh flags": "fwd_psh_flags",
    "bwd psh flags": "bwd_psh_flags",
    "fwd urg flags": "fwd_urg_flags",
    "bwd urg flags": "bwd_urg_flags",
    "fwd header length": "fwd_header_length",
    "bwd header length": "bwd_header_length",
    "fwd packets/s": "fwd_packets_s",
    "bwd packets/s": "bwd_packets_s",
    "packet length min": "packet_length_min",
    "packet length max": "packet_length_max",
    "packet length mean": "packet_length_mean",
    "packet length std": "packet_length_std",
    "packet length variance": "packet_length_variance",
    "fin flag count": "fin_flag_count",
    "syn flag count": "syn_flag_count",
    "rst flag count": "rst_flag_count",
    "psh flag count": "psh_flag_count",
    "ack flag count": "ack_flag_count",
    "urg flag count": "urg_flag_count",
    "cwe flag count": "cwe_flag_count",
    "ece flag count": "ece_flag_count",
    "down/up ratio": "down_up_ratio",
    "avg packet size": "avg_packet_size",
    "avg fwd segment size": "avg_fwd_segment_size",
    "avg bwd segment size": "avg_bwd_segment_size",
    "fwd avg bytes/bulk": "fwd_avg_bytes_bulk",
    "fwd avg packets/bulk": "fwd_avg_packets_bulk",
    "fwd avg bulk rate": "fwd_avg_bulk_rate",
    "bwd avg bytes/bulk": "bwd_avg_bytes_bulk",
    "bwd avg packets/bulk": "bwd_avg_packets_bulk",
    "bwd avg bulk rate": "bwd_avg_bulk_rate",
    "subflow fwd packets": "subflow_fwd_packets",
    "subflow fwd bytes": "subflow_fwd_bytes",
    "subflow bwd packets": "subflow_bwd_packets",
    "subflow bwd bytes": "subflow_bwd_bytes",
    "init_win_bytes_forward": "init_win_bytes_forward",
    "init_win_bytes_backward": "init_win_bytes_backward",
    "act_data_pkt_fwd": "act_data_pkt_fwd",
    "min_seg_size_forward": "min_seg_size_forward",
    "active mean": "active_mean",
    "active std": "active_std",
    "active max": "active_max",
    "active min": "active_min",
    "idle mean": "idle_mean",
    "idle std": "idle_std",
    "idle max": "idle_max",
    "idle min": "idle_min",
    "label": "label",
    "destination port": "destination_port",
    "source port": "source_port",
}


# ── ML feature selection ─────────────────────────────────────────
# These are the CICIDS2017 columns we select for the ML model.
# Feature order must be identical during training and inference.

ML_FEATURE_COLUMNS: list[str] = [
    "flow_duration",
    "total_fwd_packets",
    "total_backward_packets",
    "total_bytes",              # derived: fwd + bwd
    "flow_bytes_s",
    "flow_packets_s",
    "destination_port",
    "source_port",
    "packet_length_mean",
    "packet_length_std",
    "fwd_packet_length_mean",
    "bwd_packet_length_mean",
]


# CICIDS2017 attack label → binary
_ATTACK_LABELS: set[str] = {
    "ddos",
    "dos slowloris",
    "dos slowhttptest",
    "dos hulk",
    "dos goldeneye",
    "heartbleed",
    "web attack brute force",
    "web attack xss",
    "web attack sql injection",
    "infiltration",
    "bot",
    "portscan",
    "ftp-patator",
    "ssh-patator",
}


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize CICIDS2017 column names to clean snake_case."""
    rename_map: dict[str, str] = {}
    for col in df.columns:
        cleaned = col.strip().lower()
        if cleaned in _COLUMN_ALIASES:
            rename_map[col] = _COLUMN_ALIASES[cleaned]
        else:
            # Keep original but lowercased and stripped
            rename_map[col] = cleaned.replace(" ", "_")
    return df.rename(columns=rename_map)


def normalize_labels(df: pd.DataFrame) -> pd.DataFrame:
    """Map CICIDS2017 labels to binary BENIGN / ATTACK."""
    df["label"] = df["label"].str.strip().str.lower()
    df["label"] = df["label"].apply(
        lambda x: "ATTACK" if x in _ATTACK_LABELS else "BENIGN"
    )
    return df


def derive_total_bytes(df: pd.DataFrame) -> pd.DataFrame:
    """Derive total bytes from forward + backward packet length totals."""
    if "fwd_packets_length_total" in df.columns and "bwd_packets_length_total" in df.columns:
        df["total_bytes"] = df["fwd_packets_length_total"] + df["bwd_packets_length_total"]
    elif "flow_bytes_s" in df.columns and "flow_duration" in df.columns:
        df["total_bytes"] = df["flow_bytes_s"] * df["flow_duration"]
    else:
        df["total_bytes"] = 0.0
    return df


def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    """Clean the DataFrame: remove duplicates, handle NaN/inf, coerce types."""
    initial_rows = len(df)
    print(f"  Initial rows: {initial_rows}")

    # Remove duplicates
    df = df.drop_duplicates()
    print(f"  After dedup: {len(df)} (removed {initial_rows - len(df)})")

    # Replace inf with NaN, then fill NaN with 0
    df = df.replace([np.inf, -np.inf], np.nan)
    nan_count = df.isna().sum().sum()
    print(f"  NaN values found: {nan_count}")

    # Select only the ML feature columns + label
    available_features = [c for c in ML_FEATURE_COLUMNS if c in df.columns]
    missing = [c for c in ML_FEATURE_COLUMNS if c not in df.columns]
    if missing:
        print(f"  WARNING: Missing columns (will be filled with 0): {missing}")

    # Keep only needed columns
    keep_cols = available_features + ["label"]
    df = df[keep_cols].copy()

    # Fill any remaining NaN with 0
    df = df.fillna(0)

    # Coerce feature columns to float
    for col in available_features:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0.0)

    print(f"  Final rows: {len(df)}")
    return df


def load_csv_files(path: str) -> pd.DataFrame:
    """Load one or more CICIDS2017 CSV files."""
    path_obj = Path(path)

    if path_obj.is_file() and path_obj.suffix == ".csv":
        print(f"Loading single file: {path_obj.name}")
        return pd.read_csv(path_obj, low_memory=False)

    if path_obj.is_dir():
        csv_files = sorted(path_obj.glob("*.csv"))
        if not csv_files:
            print(f"ERROR: No CSV files found in {path_obj}")
            sys.exit(1)

        print(f"Found {len(csv_files)} CSV files in {path_obj}:")
        dfs = []
        for f in csv_files:
            print(f"  Loading {f.name}...")
            try:
                df = pd.read_csv(f, low_memory=False)
                print(f"    {len(df)} rows, {len(df.columns)} columns")
                dfs.append(df)
            except Exception as e:
                print(f"    WARNING: Failed to load {f.name}: {e}")
                continue

        if not dfs:
            print("ERROR: No files loaded successfully")
            sys.exit(1)

        return pd.concat(dfs, ignore_index=True)

    print(f"ERROR: {path_obj} is not a valid CSV file or directory")
    sys.exit(1)


def prepare_dataset(csv_path: str, output_dir: str | None = None) -> pd.DataFrame:
    """
    Full preparation pipeline for CICIDS2017 data.

    Args:
        csv_path: Path to CICIDS2017 CSV file or directory of CSVs.
        output_dir: Where to save cleaned data. Defaults to training/data/.

    Returns:
        Cleaned DataFrame ready for training.
    """
    print("=" * 60)
    print("SIH26145 — CICIDS2017 Data Preparation")
    print("=" * 60)

    # Determine output directory
    if output_dir is None:
        output_dir = str(Path(__file__).resolve().parent / "data")
    os.makedirs(output_dir, exist_ok=True)

    # Step 1: Load
    print("\n[1/6] Loading CICIDS2017 data...")
    df = load_csv_files(csv_path)
    print(f"  Total rows loaded: {len(df)}")
    print(f"  Total columns: {len(df.columns)}")

    # Step 2: Show raw column names
    print("\n[2/6] Raw column names:")
    for i, col in enumerate(df.columns):
        print(f"  {i+1:2d}. {repr(col)}")

    # Step 3: Normalize columns
    print("\n[3/6] Normalizing column names...")
    df = normalize_columns(df)
    print(f"  Normalized columns: {list(df.columns[:10])}...")

    # Step 4: Normalize labels
    print("\n[4/6] Normalizing labels to binary BENIGN/ATTACK...")
    df = normalize_labels(df)
    print(f"  Class distribution:")
    for label, count in df["label"].value_counts().items():
        print(f"    {label}: {count} ({count/len(df)*100:.1f}%)")

    # Step 5: Derive total_bytes
    print("\n[5/6] Deriving features...")
    df = derive_total_bytes(df)

    # Step 6: Clean
    print("\n[6/6] Cleaning data...")
    df = clean_data(df)

    # Verify required features exist
    available = [c for c in ML_FEATURE_COLUMNS if c in df.columns]
    print(f"\n  Available ML features ({len(available)}/{len(ML_FEATURE_COLUMNS)}):")
    for f in ML_FEATURE_COLUMNS:
        status = "✓" if f in df.columns else "✗ MISSING"
        print(f"    {status} {f}")

    # Save cleaned dataset
    csv_output = os.path.join(output_dir, "cicids2017_cleaned.csv")
    df.to_csv(csv_output, index=False)
    print(f"\n  Saved cleaned dataset: {csv_output}")
    print(f"  Shape: {df.shape}")

    # Save feature info
    feature_info = {
        "feature_columns": ML_FEATURE_COLUMNS,
        "num_features": len(ML_FEATURE_COLUMNS),
        "label_column": "label",
        "classes": ["BENIGN", "ATTACK"],
        "data_source": "CICIDS2017",
        "num_rows": len(df),
        "class_distribution": df["label"].value_counts().to_dict(),
    }
    info_path = os.path.join(output_dir, "feature_info.joblib")
    joblib.dump(feature_info, info_path)
    print(f"  Saved feature info: {info_path}")

    # Summary
    print("\n" + "=" * 60)
    print("PREPARATION COMPLETE")
    print("=" * 60)
    print(f"  Dataset: {csv_output}")
    print(f"  Rows: {len(df)}")
    print(f"  Features: {len(ML_FEATURE_COLUMNS)}")
    print(f"  Classes: {df['label'].nunique()} ({list(df['label'].unique())})")
    print(f"\n  Feature mapping:")
    print(f"  {'CICIDS2017 Source':<35} → {'ML Feature'}")
    print(f"  {'─'*35}   {'─'*25}")
    feature_sources = {
        "flow_duration": "Flow Duration",
        "total_fwd_packets": "Total Fwd Packets",
        "total_backward_packets": "Total Backward Packets",
        "total_bytes": "Fwd + Bwd Packet Length Total",
        "flow_bytes_s": "Flow Bytes/s",
        "flow_packets_s": "Flow Packets/s",
        "destination_port": "Destination Port",
        "source_port": "Source Port",
        "packet_length_mean": "Packet Length Mean",
        "packet_length_std": "Packet Length Std",
        "fwd_packet_length_mean": "Fwd Packet Length Mean",
        "bwd_packet_length_mean": "Bwd Packet Length Mean",
    }
    for feat in ML_FEATURE_COLUMNS:
        src = feature_sources.get(feat, "unknown")
        print(f"  {src:<35} → {feat}")

    print(f"\n  NOTE: sourceEntropy and destinationConcentration from the")
    print(f"  original 11-feature model are NOT available in CICIDS2017.")
    print(f"  They have been replaced with fwd_packet_length_mean and")
    print(f"  bwd_packet_length_mean which capture similar directional")
    print(f"  traffic patterns.")

    return df


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python training/prepare_cicids2017.py /path/to/MachineLearningCSV/")
        print("")
        print("Download CICIDS2017 from:")
        print("  https://www.unb.ca/cic/datasets/ids-2017.html")
        print("")
        print("Extract the MachineLearningCSV directory and pass its path.")
        sys.exit(1)

    csv_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None
    prepare_dataset(csv_path, output_path)
